//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForexBox.LanguageResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FAQRU {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FAQRU() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ForexBox.LanguageResources.FAQRU", typeof(FAQRU).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Частые вопросы:.
        /// </summary>
        internal static string faqtext1 {
            get {
                return ResourceManager.GetString("faqtext1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Как зарабатывать с помощью партнерской программы?.
        /// </summary>
        internal static string faqtext10 {
            get {
                return ResourceManager.GetString("faqtext10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В Вашем личном кабинете ForexBox, пройдите в раздел &quot;Партнерам&quot;. В этом разделе находится партнерская ссылка, с помощью которой Вы будете приглашать на наш сайт своих клиентов. За каждого активного клиента, Вы будете получать проценты. Более подробно, читайте на странице .
        /// </summary>
        internal static string faqtext11 {
            get {
                return ResourceManager.GetString("faqtext11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Партнерство.
        /// </summary>
        internal static string faqtext12 {
            get {
                return ResourceManager.GetString("faqtext12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Что такое ПАММ счет?.
        /// </summary>
        internal static string faqtext2 {
            get {
                return ResourceManager.GetString("faqtext2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПАММ счет - это инновационное решения для работы на валютном рынке Форекс как для профессионалов, так и для новичков. Принцип работы заключается в доверительном управлении Вашим счетом. Вы можете ознакомится с мониторингом нашей торговли, убедиться в доходности нашей системы и подключится к нашему ПАММ счету, дальнейшая работа будет за нами..
        /// </summary>
        internal static string faqtext3 {
            get {
                return ResourceManager.GetString("faqtext3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to С каким брокером Вы работаете?.
        /// </summary>
        internal static string faqtext4 {
            get {
                return ResourceManager.GetString("faqtext4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Компания ForexBox сотрудничает с компанией Dukascopy, которая работает с 1998 года. Dukascopy Europe IBS AS инвестиционно-брокерская компания в ЕС на 100% принадлежащая швейцарскому банку Dukascopy Bank SA. Подключившись к нашему ПАММ счету, Вы одновременно открываете счет в швейцарском банке, что дает гарантию на надежность Вашего депозита..
        /// </summary>
        internal static string faqtext5 {
            get {
                return ResourceManager.GetString("faqtext5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Какой нужно иметь минимальный депозит в швейцарском банке Dukascopy?.
        /// </summary>
        internal static string faqtext6 {
            get {
                return ResourceManager.GetString("faqtext6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для подключения к нашему ПАММ счету, Вам нужно открыть счет в Dukascopy. По условиям компании на вашем счету должно быть не меньше 5000 USD. Важно! Для клиентов не располагающими такой суммой, мы предоставляем возможность подключения к ПАММ счету без открытия счета в Dukascopy (с депозитом не меньше 500 USD). Подробнее в личном кабинете ForexBox, в разделе &quot;ПАММ счет&quot;..
        /// </summary>
        internal static string faqtext7 {
            get {
                return ResourceManager.GetString("faqtext7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Возможна ли работа с депозитом меньше допустимого минимума?.
        /// </summary>
        internal static string faqtext8 {
            get {
                return ResourceManager.GetString("faqtext8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если Ваш депозит по условиям Банка Dukascopy меньше 5000$, то Вы можете так же инвестировать в наш ПАММ но уже без открытия счета в Dukascopy. Подайте заявку для регистрации в ПАММ системе в кабинете ForexBox, указав размер Вашего депозита (не меньше 500$), и в ближайшее время мы с Вами свяжемся..
        /// </summary>
        internal static string faqtext9 {
            get {
                return ResourceManager.GetString("faqtext9", resourceCulture);
            }
        }
    }
}
