//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForexBox.LanguageResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Indexes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Indexes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ForexBox.LanguageResources.Indexes", typeof(Indexes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alertas de Negocios.
        /// </summary>
        internal static string Dukasagent {
            get {
                return ResourceManager.GetString("Dukasagent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ForexBox.
        /// </summary>
        internal static string ForexBox {
            get {
                return ResourceManager.GetString("ForexBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vamos a ayudarle a aumentar su capital de !.
        /// </summary>
        internal static string IncreaseIncome {
            get {
                return ResourceManager.GetString("IncreaseIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asociación.
        /// </summary>
        internal static string Indexpartner {
            get {
                return ResourceManager.GetString("Indexpartner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sea nuestro socio.
        /// </summary>
        internal static string Indextext1 {
            get {
                return ResourceManager.GetString("Indextext1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y recibe la posibilidad de conectar.
        /// </summary>
        internal static string Indextext2 {
            get {
                return ResourceManager.GetString("Indextext2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nuestra cuenta PAMM !.
        /// </summary>
        internal static string Indextext3 {
            get {
                return ResourceManager.GetString("Indextext3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilice nuestro.
        /// </summary>
        internal static string Indextext4 {
            get {
                return ResourceManager.GetString("Indextext4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot; Programa de Partners &quot;.
        /// </summary>
        internal static string Indextext5 {
            get {
                return ResourceManager.GetString("Indextext5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ganar mientras.
        /// </summary>
        internal static string Indextext6 {
            get {
                return ResourceManager.GetString("Indextext6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no invertir ni un centavo !.
        /// </summary>
        internal static string Indextext7 {
            get {
                return ResourceManager.GetString("Indextext7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Innovador sistema de comercio.
        /// </summary>
        internal static string InnovativeTradeSystem {
            get {
                return ResourceManager.GetString("InnovativeTradeSystem", resourceCulture);
            }
        }
    }
}
