//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForexBox.LanguageResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LoginSharedRu {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LoginSharedRu() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ForexBox.LanguageResources.LoginSharedRu", typeof(LoginSharedRu).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На сервере произошла ошибка.
        /// </summary>
        internal static string Alert {
            get {
                return ResourceManager.GetString("Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Внимание!.
        /// </summary>
        internal static string Attention {
            get {
                return ResourceManager.GetString("Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы забыли указать логин.
        /// </summary>
        internal static string Forgotlog {
            get {
                return ResourceManager.GetString("Forgotlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы забыли указать пароль.
        /// </summary>
        internal static string Forgotpas {
            get {
                return ResourceManager.GetString("Forgotpas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы ввели неправильный логин или пароль. При последующих ошибках обратитесь к администрации.
        /// </summary>
        internal static string Incorrectall {
            get {
                return ResourceManager.GetString("Incorrectall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный логин или пароль.
        /// </summary>
        internal static string Incorrectlogpas {
            get {
                return ResourceManager.GetString("Incorrectlogpas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Исправьте пожалуйста следующие ошибки:.
        /// </summary>
        internal static string Incorrectplease {
            get {
                return ResourceManager.GetString("Incorrectplease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В кабинет.
        /// </summary>
        internal static string LogInbutton {
            get {
                return ResourceManager.GetString("LogInbutton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Авторизация.
        /// </summary>
        internal static string LogInForm {
            get {
                return ResourceManager.GetString("LogInForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        internal static string Placeholderemail {
            get {
                return ResourceManager.GetString("Placeholderemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логин.
        /// </summary>
        internal static string Placeholderlogin {
            get {
                return ResourceManager.GetString("Placeholderlogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Партнерский Код.
        /// </summary>
        internal static string Placeholderpartner {
            get {
                return ResourceManager.GetString("Placeholderpartner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        internal static string Placeholderpas {
            get {
                return ResourceManager.GetString("Placeholderpas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повторите пароль.
        /// </summary>
        internal static string Placeholderpas2 {
            get {
                return ResourceManager.GetString("Placeholderpas2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необязательное поле.
        /// </summary>
        internal static string Texboxno {
            get {
                return ResourceManager.GetString("Texboxno", resourceCulture);
            }
        }
    }
}
