//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForexBox.LanguageResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PAMMuk {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PAMMuk() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ForexBox.LanguageResources.PAMMuk", typeof(PAMMuk).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПАММ рахунок.
        /// </summary>
        internal static string Pammtext1 {
            get {
                return ResourceManager.GetString("Pammtext1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FOREXBOX.
        /// </summary>
        internal static string Pammtext2 {
            get {
                return ResourceManager.GetString("Pammtext2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Представляємо Вашій увазі програму довірчого управління.
        /// </summary>
        internal static string Pammtext3 {
            get {
                return ResourceManager.GetString("Pammtext3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завдяки цьому сервісу наші клієнти можуть заробляти на Форексі, при цьому не торгуючи самостійно.
        /// </summary>
        internal static string Pammtext4 {
            get {
                return ResourceManager.GetString("Pammtext4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моніторинг рахунку знаходиться у стадії тестування, стежте за новинами..
        /// </summary>
        internal static string Pammtext5 {
            get {
                return ResourceManager.GetString("Pammtext5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Важливо!.
        /// </summary>
        internal static string Pammtext6 {
            get {
                return ResourceManager.GetString("Pammtext6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У цій торгівлі, ми не використовуємо роботів або радників.
        /// </summary>
        internal static string Pammtext7 {
            get {
                return ResourceManager.GetString("Pammtext7", resourceCulture);
            }
        }
    }
}
