//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForexBox.LanguageResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PartnerPageru {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PartnerPageru() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ForexBox.LanguageResources.PartnerPageru", typeof(PartnerPageru).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Партнерская программа.
        /// </summary>
        internal static string PartnerPagetext1 {
            get {
                return ResourceManager.GetString("PartnerPagetext1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Представляем Вашему вниманию одну из самых лучших, 
        ///                и удобных партнерских программ в интернете! 
        ///                Преимущества этой программы в том, что она не требует никаких вложений, поэтому 
        ///                дополнительный доход она сможет приносить абсолютно каждому..
        /// </summary>
        internal static string PartnerPagetext2 {
            get {
                return ResourceManager.GetString("PartnerPagetext2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Как она работает?.
        /// </summary>
        internal static string PartnerPagetext3 {
            get {
                return ResourceManager.GetString("PartnerPagetext3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Вы открываете личный кабинет у нас на сайте (займет не более 20 секунд)..
        /// </summary>
        internal static string PartnerPagetext4 {
            get {
                return ResourceManager.GetString("PartnerPagetext4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Далее в личном кабинете берете Вашу партнерскую ссылку..
        /// </summary>
        internal static string PartnerPagetext5 {
            get {
                return ResourceManager.GetString("PartnerPagetext5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. С помощью ссылки приглашаете на наш сайт клиентов..
        /// </summary>
        internal static string PartnerPagetext6 {
            get {
                return ResourceManager.GetString("PartnerPagetext6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. За каждого активного клиента, получаете 50% от каждой закрытой сделки приглашенного..
        /// </summary>
        internal static string PartnerPagetext7 {
            get {
                return ResourceManager.GetString("PartnerPagetext7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Больше клиентов - больше прибыли. Помните что Ваши партнеры тоже могут привести клиентов, с которых Вы также получите прибыль в размере 25%..
        /// </summary>
        internal static string PartnerPagetext8 {
            get {
                return ResourceManager.GetString("PartnerPagetext8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зарабатывать с ForexBox легко и просто!.
        /// </summary>
        internal static string PartnerPagetext9 {
            get {
                return ResourceManager.GetString("PartnerPagetext9", resourceCulture);
            }
        }
    }
}
