//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForexBox.LanguageResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PartnerPagees {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PartnerPagees() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ForexBox.LanguageResources.PartnerPagees", typeof(PartnerPagees).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programa de afiliados.
        /// </summary>
        internal static string PartnerPagetext1 {
            get {
                return ResourceManager.GetString("PartnerPagetext1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traiga a su atención a uno de los mejores programas , más confortables y de afiliados en Internet! Los beneficios de este programa es que no requiere ninguna inversión , por lo que los ingresos adicionales que puede aportar absolutamente todo el mundo ..
        /// </summary>
        internal static string PartnerPagetext2 {
            get {
                return ResourceManager.GetString("PartnerPagetext2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Cómo funciona ?.
        /// </summary>
        internal static string PartnerPagetext3 {
            get {
                return ResourceManager.GetString("PartnerPagetext3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.You abrir su cuenta personal en nuestro sitio web ( toma menos de 20 segundos ) ..
        /// </summary>
        internal static string PartnerPagetext4 {
            get {
                return ResourceManager.GetString("PartnerPagetext4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.Dalee gabinete personal tome su red de afiliados ..
        /// </summary>
        internal static string PartnerPagetext5 {
            get {
                return ResourceManager.GetString("PartnerPagetext5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.With por referencia invitar a los clientes a nuestro sitio web ..
        /// </summary>
        internal static string PartnerPagetext6 {
            get {
                return ResourceManager.GetString("PartnerPagetext6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.Za cada cliente activo , consigue el 50% de cada transacción cerrada invitado ..
        /// </summary>
        internal static string PartnerPagetext7 {
            get {
                return ResourceManager.GetString("PartnerPagetext7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Más clientes - más pribyli. Pomnite que sus socios también pueden conducir al cliente que usted también tendrá una ganancia de 25 %..
        /// </summary>
        internal static string PartnerPagetext8 {
            get {
                return ResourceManager.GetString("PartnerPagetext8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ganar dinero con ForexBox fácil !.
        /// </summary>
        internal static string PartnerPagetext9 {
            get {
                return ResourceManager.GetString("PartnerPagetext9", resourceCulture);
            }
        }
    }
}
