//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForexBox.LanguageResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PartnerPagezh_CHS {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PartnerPagezh_CHS() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ForexBox.LanguageResources.PartnerPagezh-CHS", typeof(PartnerPagezh_CHS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 联盟计划.
        /// </summary>
        internal static string PartnerPagetext1 {
            get {
                return ResourceManager.GetString("PartnerPagetext1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提请你注意在互联网上！优势这一计划的最好，最方便的联盟计划之一是，它不需要任何投资，所以额外的收入能带来绝对的每一个人。.
        /// </summary>
        internal static string PartnerPagetext2 {
            get {
                return ResourceManager.GetString("PartnerPagetext2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 它是如何工作的？.
        /// </summary>
        internal static string PartnerPagetext3 {
            get {
                return ResourceManager.GetString("PartnerPagetext3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1。您在我们的网站（只需不到20秒）打开你的个人帐户。.
        /// </summary>
        internal static string PartnerPagetext4 {
            get {
                return ResourceManager.GetString("PartnerPagetext4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.In个人办公室把你的友情链接。.
        /// </summary>
        internal static string PartnerPagetext5 {
            get {
                return ResourceManager.GetString("PartnerPagetext5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3。具有参照邀请客户到我们的网站。.
        /// </summary>
        internal static string PartnerPagetext6 {
            get {
                return ResourceManager.GetString("PartnerPagetext6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.Za每个活动的客户端，获得每笔交易的50 ％收盘受邀者。.
        /// </summary>
        internal static string PartnerPagetext7 {
            get {
                return ResourceManager.GetString("PartnerPagetext7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更多的客户 - 更多的利润。请记住，你的伴侣也可能导致客户，你也将获得25％的利润。.
        /// </summary>
        internal static string PartnerPagetext8 {
            get {
                return ResourceManager.GetString("PartnerPagetext8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 使与ForexBox轻松赚钱！.
        /// </summary>
        internal static string PartnerPagetext9 {
            get {
                return ResourceManager.GetString("PartnerPagetext9", resourceCulture);
            }
        }
    }
}
