//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForexBox.LanguageResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PartnerPageit {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PartnerPageit() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ForexBox.LanguageResources.PartnerPageit", typeof(PartnerPageit).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programma di affiliazione.
        /// </summary>
        internal static string PartnerPagetext1 {
            get {
                return ResourceManager.GetString("PartnerPagetext1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portare alla vostra attenzione uno dei programmi migliori , più confortevoli e affiliazione su Internet ! 
        ///                I vantaggi di questo programma è che non richiede alcun investimento , quindi entrate supplementari che possono portare assolutamente tutti ..
        /// </summary>
        internal static string PartnerPagetext2 {
            get {
                return ResourceManager.GetString("PartnerPagetext2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Come funziona ?.
        /// </summary>
        internal static string PartnerPagetext3 {
            get {
                return ResourceManager.GetString("PartnerPagetext3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.Non aprire il tuo account personale sul nostro sito web ( richiede meno di 20 secondi ) ..
        /// </summary>
        internal static string PartnerPagetext4 {
            get {
                return ResourceManager.GetString("PartnerPagetext4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.Dalee armadietto personale prenditi il ​​tuo link di affiliazione ..
        /// </summary>
        internal static string PartnerPagetext5 {
            get {
                return ResourceManager.GetString("PartnerPagetext5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.With con riferimento invitare i clienti al nostro sito web ..
        /// </summary>
        internal static string PartnerPagetext6 {
            get {
                return ResourceManager.GetString("PartnerPagetext6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.Za ogni cliente attivo , ottiene il 50 % di ogni transazione chiusa invitato ..
        /// </summary>
        internal static string PartnerPagetext7 {
            get {
                return ResourceManager.GetString("PartnerPagetext7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altri clienti - più pribyli. Pomnite che i partner possono portare anche al cliente che si riceverà anche un profitto del 25 % ..
        /// </summary>
        internal static string PartnerPagetext8 {
            get {
                return ResourceManager.GetString("PartnerPagetext8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guadagna con ForexBox facile !.
        /// </summary>
        internal static string PartnerPagetext9 {
            get {
                return ResourceManager.GetString("PartnerPagetext9", resourceCulture);
            }
        }
    }
}
