//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForexBox.LanguageResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PartnerPageen {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PartnerPageen() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ForexBox.LanguageResources.PartnerPageen", typeof(PartnerPageen).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner program.
        /// </summary>
        internal static string PartnerPagetext1 {
            get {
                return ResourceManager.GetString("PartnerPagetext1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We present one of the best to Your attention, 
        ///                and comfortable partner programs in the internet! 
        ///                Advantages of this program are in that she requires no investments, therefore 
        ///                an additional acuests she will be able to bring to absolutely each..
        /// </summary>
        internal static string PartnerPagetext2 {
            get {
                return ResourceManager.GetString("PartnerPagetext2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How does she work?.
        /// </summary>
        internal static string PartnerPagetext3 {
            get {
                return ResourceManager.GetString("PartnerPagetext3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. you open the personal cabinet for us on a web-site(will occupy no more than 20 seconds)..
        /// </summary>
        internal static string PartnerPagetext4 {
            get {
                return ResourceManager.GetString("PartnerPagetext4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Further in the personal cabinet take Your partner reference..
        /// </summary>
        internal static string PartnerPagetext5 {
            get {
                return ResourceManager.GetString("PartnerPagetext5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. By means of reference invite on our web-site of clients..
        /// </summary>
        internal static string PartnerPagetext6 {
            get {
                return ResourceManager.GetString("PartnerPagetext6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. For every active client, get 50% from every closed transaction of invited..
        /// </summary>
        internal static string PartnerPagetext7 {
            get {
                return ResourceManager.GetString("PartnerPagetext7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More clients - more profit. Remember that Your partners can bring clients over, from that you also will get a profit in size of 25%, too..
        /// </summary>
        internal static string PartnerPagetext8 {
            get {
                return ResourceManager.GetString("PartnerPagetext8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earning with ForexBox easily and simply!.
        /// </summary>
        internal static string PartnerPagetext9 {
            get {
                return ResourceManager.GetString("PartnerPagetext9", resourceCulture);
            }
        }
    }
}
