//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForexBox.LanguageResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RegisterShareden {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RegisterShareden() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ForexBox.LanguageResources.RegisterShareden", typeof(RegisterShareden).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Such mail is already used.
        /// </summary>
        internal static string Incorrectemail {
            get {
                return ResourceManager.GetString("Incorrectemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect format of e-mail.
        /// </summary>
        internal static string Incorrectemailformat {
            get {
                return ResourceManager.GetString("Incorrectemailformat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Such name is already used.
        /// </summary>
        internal static string Incorrectname {
            get {
                return ResourceManager.GetString("Incorrectname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not coincide.
        /// </summary>
        internal static string Incorrectwrite2pas {
            get {
                return ResourceManager.GetString("Incorrectwrite2pas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You forgot to specify mail.
        /// </summary>
        internal static string Incorrectwriteemail {
            get {
                return ResourceManager.GetString("Incorrectwriteemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You forgot to specify the reiteration of password.
        /// </summary>
        internal static string Incorrectwritepas {
            get {
                return ResourceManager.GetString("Incorrectwritepas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum length of password is 6 symbols.
        /// </summary>
        internal static string Incorrectwritepaslong {
            get {
                return ResourceManager.GetString("Incorrectwritepaslong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Become a partner.
        /// </summary>
        internal static string Registerbutton {
            get {
                return ResourceManager.GetString("Registerbutton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration went well! you can enter the personal cabinet..
        /// </summary>
        internal static string Registerfinishes {
            get {
                return ResourceManager.GetString("Registerfinishes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration was not successful! Try once again or appeal to administration..
        /// </summary>
        internal static string Registernotfinishes {
            get {
                return ResourceManager.GetString("Registernotfinishes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        internal static string Registertext {
            get {
                return ResourceManager.GetString("Registertext", resourceCulture);
            }
        }
    }
}
