//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForexBox.LanguageResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RegisterSharedit {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RegisterSharedit() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ForexBox.LanguageResources.RegisterSharedit", typeof(RegisterSharedit).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questa email è già in uso.
        /// </summary>
        internal static string Incorrectemail {
            get {
                return ResourceManager.GetString("Incorrectemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato di posta elettronica non valido.
        /// </summary>
        internal static string Incorrectemailformat {
            get {
                return ResourceManager.GetString("Incorrectemailformat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questo nome è già in uso.
        /// </summary>
        internal static string Incorrectname {
            get {
                return ResourceManager.GetString("Incorrectname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le password non corrispondono.
        /// </summary>
        internal static string Incorrectwrite2pas {
            get {
                return ResourceManager.GetString("Incorrectwrite2pas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si dimentica di posta elettronica.
        /// </summary>
        internal static string Incorrectwriteemail {
            get {
                return ResourceManager.GetString("Incorrectwriteemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hai dimenticato di specificare la password di ripetizione.
        /// </summary>
        internal static string Incorrectwritepas {
            get {
                return ResourceManager.GetString("Incorrectwritepas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lunghezza minima della password è di 6 caratteri.
        /// </summary>
        internal static string Incorrectwritepaslong {
            get {
                return ResourceManager.GetString("Incorrectwritepaslong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diventare partner.
        /// </summary>
        internal static string Registerbutton {
            get {
                return ResourceManager.GetString("Registerbutton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La registrazione ha avuto successo !.
        /// </summary>
        internal static string Registerfinishes {
            get {
                return ResourceManager.GetString("Registerfinishes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La registrazione non ha avuto successo !.
        /// </summary>
        internal static string Registernotfinishes {
            get {
                return ResourceManager.GetString("Registernotfinishes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrazione.
        /// </summary>
        internal static string Registertext {
            get {
                return ResourceManager.GetString("Registertext", resourceCulture);
            }
        }
    }
}
