//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForexBox.LanguageResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RegisterSharedzh_CHS {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RegisterSharedzh_CHS() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ForexBox.LanguageResources.RegisterSharedzh-CHS", typeof(RegisterSharedzh_CHS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 此电子邮件已被使用.
        /// </summary>
        internal static string Incorrectemail {
            get {
                return ResourceManager.GetString("Incorrectemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无效的电子邮件格式.
        /// </summary>
        internal static string Incorrectemailformat {
            get {
                return ResourceManager.GetString("Incorrectemailformat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 此名称已被使用.
        /// </summary>
        internal static string Incorrectname {
            get {
                return ResourceManager.GetString("Incorrectname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码不匹配.
        /// </summary>
        internal static string Incorrectwrite2pas {
            get {
                return ResourceManager.GetString("Incorrectwrite2pas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 你忘了邮件.
        /// </summary>
        internal static string Incorrectwriteemail {
            get {
                return ResourceManager.GetString("Incorrectwriteemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 你忘了指定重复密码.
        /// </summary>
        internal static string Incorrectwritepas {
            get {
                return ResourceManager.GetString("Incorrectwritepas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最小密码长度为6个字符.
        /// </summary>
        internal static string Incorrectwritepaslong {
            get {
                return ResourceManager.GetString("Incorrectwritepaslong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成为合作伙伴.
        /// </summary>
        internal static string Registerbutton {
            get {
                return ResourceManager.GetString("Registerbutton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注册成功！.
        /// </summary>
        internal static string Registerfinishes {
            get {
                return ResourceManager.GetString("Registerfinishes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注册没有成功！.
        /// </summary>
        internal static string Registernotfinishes {
            get {
                return ResourceManager.GetString("Registernotfinishes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注册.
        /// </summary>
        internal static string Registertext {
            get {
                return ResourceManager.GetString("Registertext", resourceCulture);
            }
        }
    }
}
